### ISSUE TITLE
Overseas

### ISSUE THREAD

**Issue by johangithub** [jlepird/next-gen-assignments#3]
Hi, I'm new here. I am just learning the codebase and I see that Alabama is flagged as Overseas. Is this on purpose? Maybe you meant to say AK?

https://github.com/jlepird/next-gen-assignments/blob/f0162b703d88cc720770f132e4e011f5d3cd0dd0/billets/find.php#L450-L457
```javascript
        var conus = billets.dimension(function(x){
            if ("state" in x){
               return x.state == "OCONUS" || x.state == "HI" || x.state == "AL" ? "OCONUS" : "CONUS";  
            } else {
                return "(Unknown)";
            }
            
        });
        var conusGroup = conus.group();
```

**Comment by jlepird** [comment]
Although Alabama may feel like a different country, I guess it should be included as part of CONUS.
