### ISSUE TITLE
Invert and other helper functions

### ISSUE THREAD

**Issue by johangithub** [jlepird/next-gen-assignments#4]
I saw the use of custom invert function [here](https://github.com/jlepird/next-gen-assignments/blob/f0162b703d88cc720770f132e4e011f5d3cd0dd0/billets/find.php#L594-L606). There's a javascript library called lodash.js which will help you with array/object manipulation such as invert. I'd recommend going through the doc [here](https://lodash.com/docs/4.17.4).
Your code will go from this:
```js
var invert = function (obj) {
          var new_obj = {};
          for (var prop in obj) {
                if (obj.hasOwnProperty(prop)) {
                    new_obj[obj[prop]] = prop;
                }
            }
      return new_obj;
        };
        var invertedMonths = invert(monthDisplay);
```
to this:
```js
var invertedMonths = _.invert(monthDisplay)
```

**Comment by jlepird** [comment]
Done-- good find on the library!
